name: Format, lint and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run_tests:
    name: Install, check and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"  # Update regularly

      - name: Format check with ruff
        run: uv run ruff format --check

      - name: Linting check with ruff
        run: uv run ruff check

      - name: Test with pytest
        run: uv run pytest
